"""
NIMS Resource Typing Library — Seed Data
Source: FEMA NIMS Resource Typing Library Tool (RTLT), rtlt.preptoolkit.fema.gov
FEMA Resource Typing Definitions published under public domain.
Compiled for offline use in FieldCommand IMS.
Format: (nims_id, kind, type_level, category, mission_area, description, min_personnel, capabilities, metric_notes)
"""

NIMS_RESOURCE_TYPES = [
    # ── FIRE / HAZARDOUS MATERIALS ────────────────────────────────────────────
    # Engines
    ('1-508-1001','Engine','Type I','Fire','Fire/Hazardous Materials',
     'Engine – Type I (Structure)',4,
     'Structure fire suppression; 1000 GPM pump; 400 gal tank; hose, SCBA, tools',
     '1000 GPM pump, 400 gal tank, 1200 ft 2.5" hose, 4 personnel'),
    ('1-508-1002','Engine','Type II','Fire','Fire/Hazardous Materials',
     'Engine – Type II (Structure)',3,
     'Structure fire suppression; 500 GPM pump; 400 gal tank',
     '500 GPM pump, 400 gal tank, 1000 ft 2.5" hose, 3 personnel'),
    ('1-508-1003','Engine','Type III','Fire','Fire/Hazardous Materials',
     'Engine – Type III (Wildland/Interface)',3,
     'Wildland/interface fire; off-road capability; 120 GPM pump; 500 gal tank',
     '120 GPM pump, 500 gal tank, off-road, 3 personnel'),
    ('1-508-1004','Engine','Type IV','Fire','Fire/Hazardous Materials',
     'Engine – Type IV (Wildland)',3,
     'Initial attack wildland; 50 GPM pump; 750 gal tank; off-road',
     '50 GPM pump, 750 gal tank, off-road, 3 personnel'),
    ('1-508-1005','Engine','Type V','Fire','Fire/Hazardous Materials',
     'Engine – Type V (Wildland)',2,
     'Initial attack wildland; 50 GPM pump; 400 gal tank; off-road',
     '50 GPM pump, 400 gal tank, off-road, 2-3 personnel'),
    ('1-508-1006','Engine','Type VI','Fire','Fire/Hazardous Materials',
     'Engine – Type VI (Patrol/Wildland)',2,
     'Patrol unit wildland; 30 GPM pump; 150 gal tank; off-road',
     '30 GPM pump, 150 gal tank, light off-road, 2 personnel'),
    ('1-508-1007','Engine','Type VII','Fire','Fire/Hazardous Materials',
     'Engine – Type VII (Patrol)',1,
     'Patrol/initial attack; 10 GPM pump; 50 gal tank',
     '10 GPM pump, 50 gal tank, 1-2 personnel'),
    # Hand Crews
    ('1-508-1010','Hand Crew','Type I','Fire','Fire/Hazardous Materials',
     'Hand Crew – Type I (Interagency Hotshot Crew)',20,
     'Highest trained/experienced wildland hand crew; IHC certified; self-sufficient 2 weeks',
     '20 personnel, IHC certification, capable of most difficult terrain/conditions'),
    ('1-508-1011','Hand Crew','Type II','Fire','Fire/Hazardous Materials',
     'Hand Crew – Type II',20,
     'Experienced wildland hand crew; chainsaw capability; 2-week deployment',
     '20 personnel, chainsaw operators, 2-week deployment capable'),
    ('1-508-1012','Hand Crew','Type II-IA','Fire','Fire/Hazardous Materials',
     'Hand Crew – Type II Initial Attack',10,
     'Initial attack hand crew; faster mobilization; 10 personnel',
     '10 personnel, faster mobilization than Type II'),
    # Water Tenders
    ('1-508-1020','Water Tender','Type I','Fire','Fire/Hazardous Materials',
     'Water Tender – Type I (Tactical)',3,
     'Tactical water tender; 250 GPM pump; 4000 gal minimum; off-road capable',
     '250 GPM pump, 4000+ gal, off-road, 3 personnel'),
    ('1-508-1021','Water Tender','Type II','Fire','Fire/Hazardous Materials',
     'Water Tender – Type II (Tactical)',2,
     'Tactical water tender; 200 GPM pump; 2500 gal minimum',
     '200 GPM pump, 2500+ gal, 2-3 personnel'),
    ('1-508-1022','Water Tender','Type III','Fire','Fire/Hazardous Materials',
     'Water Tender – Type III (Support)',2,
     'Support water tender; 200 GPM pump; 1500 gal minimum; highway capable',
     '200 GPM pump, 1500+ gal, highway, 2 personnel'),
    # Bulldozers
    ('1-508-1030','Bulldozer','Type I','Fire','Fire/Hazardous Materials',
     'Bulldozer – Type I (Heavy)',1,
     'Heavy dozers; >200 HP; D8/D9 class; most soil types/slopes',
     '>200 HP, D8/D9 class or equivalent, heavy blade'),
    ('1-508-1031','Bulldozer','Type II','Fire','Fire/Hazardous Materials',
     'Bulldozer – Type II (Medium)',1,
     'Medium dozers; 100-200 HP; D6/D7 class',
     '100-200 HP, D6/D7 class or equivalent, medium blade'),
    ('1-508-1032','Bulldozer','Type III','Fire','Fire/Hazardous Materials',
     'Bulldozer – Type III (Light)',1,
     'Light dozers; 50-100 HP; D4/D5 class; lighter terrain',
     '50-100 HP, D4/D5 class or equivalent'),
    # Helicopters (Fire)
    ('1-508-1040','Helicopter','Type I','Fire','Fire/Hazardous Materials',
     'Helicopter – Type I (Heavy Fire)',3,
     'Heavy fire helicopter; 700+ gal tank/bucket; 5000+ lb payload',
     '700+ gal tank, 5000+ lb payload, >700 HP, 5+ personnel capacity'),
    ('1-508-1041','Helicopter','Type II','Fire','Fire/Hazardous Materials',
     'Helicopter – Type II (Medium Fire)',2,
     'Medium fire helicopter; 300 gal tank/bucket; 2500+ lb payload',
     '300 gal tank, 2500+ lb payload, 9+ personnel capacity'),
    ('1-508-1042','Helicopter','Type III','Fire','Fire/Hazardous Materials',
     'Helicopter – Type III (Light Fire)',1,
     'Light fire helicopter; 100 gal tank/bucket; 1200+ lb payload',
     '100 gal tank, 1200+ lb payload, reconnaissance/initial attack'),
    # Airtankers
    ('1-508-1050','Airtanker','Single Engine','Fire','Fire/Hazardous Materials',
     'Airtanker – Single Engine (SEAT)',1,
     'Single engine airtanker; 800 gal retardant; initial attack',
     '800 gal retardant capacity, rapid turnaround'),
    ('1-508-1051','Airtanker','Multi-Engine','Fire','Fire/Hazardous Materials',
     'Airtanker – Multi-Engine',2,
     'Multi-engine air tanker; 1800-3000 gal retardant',
     '1800-3000 gal retardant capacity'),
    ('1-508-1052','Airtanker','Very Large','Fire','Fire/Hazardous Materials',
     'Very Large Airtanker (VLAT)',4,
     'Very large airtanker; 10,000+ gal retardant; DC-10/747 class',
     '10,000+ gal retardant, DC-10/747/C-130 class'),
    # HazMat
    ('1-508-1060','HazMat Team','Type I','Fire','Fire/Hazardous Materials',
     'Hazardous Materials Response Team – Type I',10,
     'Full offensive/defensive HazMat response; Level A entry; decon; monitoring',
     '10+ personnel, Level A suits, detection equipment, decon capability'),
    ('1-508-1061','HazMat Team','Type II','Fire','Fire/Hazardous Materials',
     'Hazardous Materials Response Team – Type II',6,
     'Defensive HazMat response; Level B entry; monitoring; plugging/patching',
     '6+ personnel, Level B entry, monitoring, basic mitigation'),
    # Aerial Apparatus
    ('4-508-1273','Aerial Apparatus','Type I','Fire','Fire/Hazardous Materials',
     'Aerial Apparatus – Type I (Ladder/Platform)',3,
     '100+ ft ladder or platform; 1500 GPM pump; 200 gal tank; SCBA',
     '100+ ft aerial, 1500 GPM, 3-4 personnel'),
    ('4-508-1274','Aerial Apparatus','Type II','Fire','Fire/Hazardous Materials',
     'Aerial Apparatus – Type II (Ladder/Platform)',3,
     '75+ ft ladder or platform; 1500 GPM pump',
     '75+ ft aerial, 1500 GPM, 3-4 personnel'),
    ('4-508-1275','Aerial Apparatus','Type III','Fire','Fire/Hazardous Materials',
     'Aerial Apparatus – Type III (Ladder)',2,
     '55+ ft ladder; 1500 GPM pump',
     '55+ ft aerial, 1500 GPM, 2-3 personnel'),

    # ── SEARCH AND RESCUE ────────────────────────────────────────────────────
    ('8-508-1001','SAR Team','Type I','Search and Rescue','Search and Rescue',
     'Search and Rescue Team – Type I (Ground)',6,
     'Technical ground SAR; all terrain; night operations; medical support; 72hr self-sufficient',
     '6 personnel, technical rescue, medical, navigation, 72hr self-sufficient'),
    ('8-508-1002','SAR Team','Type II','Search and Rescue','Search and Rescue',
     'Search and Rescue Team – Type II (Ground)',4,
     'Ground SAR; tracking; wilderness medicine; 24hr self-sufficient',
     '4 personnel, tracking, wilderness medicine, 24hr ops'),
    ('8-508-1003','SAR Team','Type III','Search and Rescue','Search and Rescue',
     'Search and Rescue Team – Type III (Ground)',4,
     'Basic ground SAR; urban and suburban; daylight operations',
     '4 personnel, basic SAR, urban/suburban terrain'),
    ('8-508-1010','Swift Water Rescue Team','Type I','Search and Rescue','Search and Rescue',
     'Swift Water Rescue Team – Type I',6,
     'Technical swift water rescue; Class IV/V water; boat and swimmer ops',
     '6 personnel, Class IV/V water, boat ops, swift water swimmers'),
    ('8-508-1011','Swift Water Rescue Team','Type II','Search and Rescue','Search and Rescue',
     'Swift Water Rescue Team – Type II',4,
     'Swift water rescue; Class III water; shore-based and boat ops',
     '4 personnel, Class III water, shore-based and boat'),
    ('8-508-1020','Urban Search and Rescue Team','Type I','Search and Rescue','Search and Rescue',
     'Urban Search and Rescue (US&R) Team – Type I (Heavy)',80,
     'Full FEMA US&R task force; structural collapse; confined space; 72hr self-sufficient',
     '80 personnel, 24hr ops, K9, medical, heavy rescue tools'),
    ('8-508-1021','Urban Search and Rescue Team','Type II','Search and Rescue','Search and Rescue',
     'Urban Search and Rescue Team – Type II (Medium)',35,
     'Medium US&R team; structural collapse; 24hr operations',
     '35 personnel, structural collapse, confined space, medical'),
    ('8-508-1022','Urban Search and Rescue Team','Type III','Search and Rescue','Search and Rescue',
     'Urban Search and Rescue Team – Type III (Light)',8,
     'Light US&R; surface victim rescue; basic structural assessment',
     '8 personnel, surface rescue, basic tools'),
    ('8-508-1030','Canine Search Team','Type I','Search and Rescue','Search and Rescue',
     'Canine Search Team – Type I',2,
     'Certified disaster/wilderness search dog; night capable; handler and dog certified FEMA/NASAR',
     '1 handler + 1 dog, FEMA/NASAR certified, 12hr ops'),
    ('8-508-1031','Canine Search Team','Type II','Search and Rescue','Search and Rescue',
     'Canine Search Team – Type II',2,
     'Certified SAR dog; wilderness tracking; basic handler certification',
     '1 handler + 1 dog, basic certification'),
    ('8-508-1007','Air Search Team','Fixed-Wing','Search and Rescue','Search and Rescue',
     'Air Search Team – Fixed-Wing',2,
     'Fixed-wing aircraft for aerial search; observer equipped; ELT/PLB detection',
     '1 pilot + 1 observer, ELT detection, daylight ops'),
    ('8-508-1008','Airborne Reconnaissance','Rotary-Wing','Search and Rescue','Search and Rescue',
     'Airborne Reconnaissance – Rotary-Wing (Helicopter)',2,
     'Helicopter search and reconnaissance; hoist capability; forward observer',
     '2-4 crew, low-altitude capable, hoist optional'),

    # ── EMERGENCY MEDICAL SERVICES ────────────────────────────────────────────
    ('3-508-1001','Ambulance','Type I','Medical','Emergency Medical Services',
     'Ambulance – Type I (ALS Ground)',2,
     'Advanced Life Support ground ambulance; modular body on truck chassis; ALS equipment',
     '2 personnel (paramedic + EMT), ALS equipment, Type I chassis'),
    ('3-508-1002','Ambulance','Type II','Medical','Emergency Medical Services',
     'Ambulance – Type II (ALS/BLS Van)',2,
     'ALS or BLS ambulance; van-type body; standard road use',
     '2 personnel, ALS or BLS, van body'),
    ('3-508-1003','Ambulance','Type III','Medical','Emergency Medical Services',
     'Ambulance – Type III (ALS Modular)',2,
     'ALS modular body on van chassis; most common type',
     '2 personnel, ALS equipment, modular body on van chassis'),
    ('3-508-1004','Ambulance','Type IV','Medical','Emergency Medical Services',
     'Ambulance – Type IV (BLS)',2,
     'Basic Life Support ambulance; transport only; non-ALS',
     '2 personnel, BLS only, transport'),
    ('3-508-1010','Mass Casualty Unit','Type I','Medical','Emergency Medical Services',
     'Mass Casualty Incident (MCI) Unit – Type I',5,
     'Large MCI; 100+ patient capacity; treatment area equipment; triage supplies',
     '5+ personnel, 100+ patient capacity, full treatment area setup'),
    ('3-508-1011','Mass Casualty Unit','Type II','Medical','Emergency Medical Services',
     'Mass Casualty Incident (MCI) Unit – Type II',3,
     'Medium MCI; 25-100 patient capacity; treatment supplies',
     '3+ personnel, 25-100 patient capacity'),
    ('3-508-1012','Mass Casualty Unit','Type III','Medical','Emergency Medical Services',
     'Mass Casualty Incident (MCI) Unit – Type III',2,
     'Small MCI; up to 25 patients; triage and treatment start',
     '2 personnel, up to 25 patients'),
    ('3-508-1020','Medical Strike Team','Type I','Medical','Emergency Medical Services',
     'Medical Strike Team – Type I (ALS)',10,
     'ALS strike team; 5 ALS ambulances + supervisor; coordinated medical response',
     '10+ personnel, 5 ALS ambulances, strike team leader'),
    ('3-508-1030','Air Ambulance','Rotary-Wing','Medical','Emergency Medical Services',
     'Air Ambulance – Rotary-Wing (Critical Care Transport)',2,
     'Critical care helicopter transport; HEMS; physician/CCRN capable',
     '2-3 crew + 1-2 medical crew, critical care equipment, night capable'),
    ('3-508-1031','Air Ambulance','Fixed-Wing','Medical','Emergency Medical Services',
     'Air Ambulance – Fixed-Wing (Critical Care)',2,
     'Fixed-wing critical care transport; inter-facility; long range',
     '2 flight crew + 1-2 medical crew, IFR capable, pressurized'),

    # ── PUBLIC WORKS / ENGINEERING ────────────────────────────────────────────
    ('5-508-1001','Excavator','Type I','Public Works','Public Works and Engineering',
     'Excavator – Type I (Heavy)',1,
     'Heavy excavator; >80,000 lb operating weight; large debris removal',
     '>80,000 lb, 30+ ton class, large bucket, heavy debris'),
    ('5-508-1002','Excavator','Type II','Public Works','Public Works and Engineering',
     'Excavator – Type II (Medium)',1,
     'Medium excavator; 40,000-80,000 lb; general debris removal',
     '40,000-80,000 lb, 15-30 ton class'),
    ('5-508-1003','Excavator','Type III','Public Works','Public Works and Engineering',
     'Excavator – Type III (Light)',1,
     'Light excavator; <40,000 lb; confined areas; light debris',
     '<40,000 lb, compact, confined space capable'),
    ('5-508-1010','Front End Loader','Type I','Public Works','Public Works and Engineering',
     'Loader – Type I (Heavy)',1,
     'Heavy front-end loader; >4.0 yd³ bucket; large debris and fill',
     '>4.0 yd³ bucket capacity, heavy debris and material moving'),
    ('5-508-1011','Front End Loader','Type II','Public Works','Public Works and Engineering',
     'Loader – Type II (Medium)',1,
     'Medium front-end loader; 2.0-4.0 yd³ bucket',
     '2.0-4.0 yd³ bucket'),
    ('5-508-1020','Dump Truck','Type I','Public Works','Public Works and Engineering',
     'Dump Truck – Type I (Heavy)',1,
     'Heavy dump truck; >18 yd³ capacity; semi-trailer type',
     '>18 yd³, 40+ ton GVW'),
    ('5-508-1021','Dump Truck','Type II','Public Works','Public Works and Engineering',
     'Dump Truck – Type II (Medium)',1,
     'Medium dump truck; 10-18 yd³ capacity; tandem axle',
     '10-18 yd³, tandem axle, standard payload'),
    ('5-508-1022','Dump Truck','Type III','Public Works','Public Works and Engineering',
     'Dump Truck – Type III (Light)',1,
     'Light dump truck; <10 yd³ capacity; single axle',
     '<10 yd³, single axle, light duty'),
    ('5-508-1030','Generator','Type I','Public Works','Public Works and Engineering',
     'Generator – Type I (Large)',1,
     'Large generator; 100-500 kW; mobile trailer-mounted; 3-phase capable',
     '100-500 kW output, trailer-mounted, 3-phase, 72hr fuel'),
    ('5-508-1031','Generator','Type II','Public Works','Public Works and Engineering',
     'Generator – Type II (Medium)',1,
     'Medium generator; 20-100 kW; towable; 3-phase capable',
     '20-100 kW, towable, 3-phase available'),
    ('5-508-1032','Generator','Type III','Public Works','Public Works and Engineering',
     'Generator – Type III (Small)',1,
     'Small generator; 2-20 kW; portable; single phase',
     '2-20 kW, portable, single phase'),
    ('5-508-1040','Light Tower','Type I','Public Works','Public Works and Engineering',
     'Light Tower – Type I (High Output)',1,
     'High-output light tower; 4000W+ output; 360° illumination; 30+ ft mast',
     '4000W+, 30+ ft pneumatic mast, 360° coverage'),
    ('5-508-1041','Light Tower','Type II','Public Works','Public Works and Engineering',
     'Light Tower – Type II (Standard)',1,
     'Standard light tower; 2000W; trailer-mounted; 20 ft mast',
     '2000W, 20 ft mast, trailer-mounted'),

    # ── MASS CARE / SHELTER ───────────────────────────────────────────────────
    ('6-508-1001','Emergency Shelter','Type I','Mass Care','Mass Care Services',
     'Emergency Shelter – Type I (Large)',10,
     'Large emergency shelter; 500+ occupant capacity; self-contained; 30-day operations',
     '500+ occupants, 30-day, feeding, medical support, registration'),
    ('6-508-1002','Emergency Shelter','Type II','Mass Care','Mass Care Services',
     'Emergency Shelter – Type II (Medium)',5,
     'Medium emergency shelter; 250-500 occupants; 14-day operations',
     '250-500 occupants, 14-day, basic feeding and registration'),
    ('6-508-1003','Emergency Shelter','Type III','Mass Care','Mass Care Services',
     'Emergency Shelter – Type III (Small)',3,
     'Small emergency shelter; up to 250 occupants; 72hr initial operations',
     'Up to 250 occupants, 72hr initial, basic services'),
    ('6-508-1010','Mobile Kitchen','Type I','Mass Care','Mass Care Services',
     'Mobile Kitchen – Type I (Large)',5,
     'Large mobile kitchen; 10,000+ meals/day; self-contained; trailer-mounted',
     '10,000+ meals/day, self-contained, trailer-mounted'),
    ('6-508-1011','Mobile Kitchen','Type II','Mass Care','Mass Care Services',
     'Mobile Kitchen – Type II (Medium)',3,
     'Medium mobile kitchen; 1,500-10,000 meals/day; truck-mounted',
     '1,500-10,000 meals/day'),
    ('6-508-1012','Mobile Kitchen','Type III','Mass Care','Mass Care Services',
     'Mobile Kitchen – Type III (Small)',2,
     'Small mobile kitchen; 300-1,500 meals/day; truck or trailer',
     '300-1,500 meals/day'),

    # ── COMMUNICATIONS ────────────────────────────────────────────────────────
    ('2-508-1001','Communications Unit','Type I','Communications','Incident Management',
     'Mobile Communications Unit – Type I (Full)',8,
     'Full field communications; satellite, VHF/UHF, HF, P25, data; 24hr ops; self-powered',
     '8 personnel, satellite uplink, VHF/UHF/HF/P25, data, 72hr ops'),
    ('2-508-1002','Communications Unit','Type II','Communications','Incident Management',
     'Mobile Communications Unit – Type II (Standard)',4,
     'Standard field comms; VHF/UHF/P25; satellite optional; 24hr ops',
     '4 personnel, VHF/UHF/P25, 24hr ops, trailer-mounted'),
    ('2-508-1003','Communications Unit','Type III','Communications','Incident Management',
     'Mobile Communications Unit – Type III (Tactical)',2,
     'Tactical field comms; VHF/UHF; portable or vehicle-mounted; 12hr ops',
     '2 personnel, VHF/UHF, vehicle or portable, 12hr ops'),
    ('2-508-1037','Airborne Communications Relay Team','Fixed-Wing','Communications','Incident Management',
     'Airborne Communications Relay Team – Fixed-Wing',2,
     'Fixed-wing aircraft providing airborne radio relay; VHF/UHF retransmission',
     '2 crew, VHF/UHF relay, 4-6hr endurance'),
    ('2-508-1038','Airborne Communications Relay','Fixed-Wing','Communications','Incident Management',
     'Airborne Communications Relay – Fixed-Wing (CAP)',2,
     'Civil Air Patrol airborne radio relay; volunteer fixed-wing; VHF relay',
     '2 crew, CAP volunteer, VHF relay, coordination'),
    ('2-508-1040','Satellite Communications Unit','Type I','Communications','Incident Management',
     'Satellite Communications Unit – Type I',2,
     'Satellite voice and data; broadband internet; video teleconferencing; mobile',
     '2 personnel, broadband satellite, video capable, mobile'),
    ('2-508-1041','Satellite Communications Unit','Type II','Communications','Incident Management',
     'Satellite Communications Unit – Type II',1,
     'Satellite voice and basic data; BGAN/VSAT; portable',
     '1 personnel, BGAN or VSAT, voice and data'),

    # ── INCIDENT MANAGEMENT ───────────────────────────────────────────────────
    ('2-508-2001','Incident Management Team','Type I','Incident Management','Incident Management',
     'Incident Management Team – Type I (National/All-Hazards)',50,
     'National-level IMT; all-hazards; fully self-contained; 100% position fill; 14-day ops',
     '50+ personnel, national deployment, all ICS positions, fully self-sufficient'),
    ('2-508-2002','Incident Management Team','Type II','Incident Management','Incident Management',
     'Incident Management Team – Type II (Regional/State)',35,
     'Regional/state IMT; all-hazards; most ICS positions; 14-day ops',
     '35+ personnel, state/regional, most ICS positions'),
    ('2-508-2003','Incident Management Team','Type III','Incident Management','Incident Management',
     'Incident Management Team – Type III (Local/Area)',15,
     'Local/area IMT; key ICS positions; multi-operational period capability',
     '15+ personnel, local/area, key ICS positions'),
    ('2-508-2004','Incident Management Team','Type IV','Incident Management','Incident Management',
     'Incident Management Team – Type IV (Initial Attack)',5,
     'Initial attack IMT; single or short operational period; locally assembled',
     '5+ personnel, initial attack, local resources'),
    ('2-508-2010','Area Command Team','Type I','Incident Management','Incident Management',
     'Area Command Team – Type I',10,
     'Oversees multiple Type I/II incidents; area command functions; unified command capable',
     '10 personnel, multi-incident coordination, unified command capable'),
    ('2-508-2020','Mobile Command Post','Type I','Incident Management','Incident Management',
     'Mobile Command Post – Type I (Large)',4,
     'Large mobile ICP; 12+ workstations; video display; satellite; generator; full ICS setup',
     '12+ workstations, satellite, generator, video display, trailer'),
    ('2-508-2021','Mobile Command Post','Type II','Incident Management','Incident Management',
     'Mobile Command Post – Type II (Medium)',2,
     'Medium mobile command; 6+ workstations; communications suite; generator',
     '6+ workstations, comms suite, generator, vehicle'),
    ('2-508-2022','Mobile Command Post','Type III','Incident Management','Incident Management',
     'Mobile Command Post – Type III (Tactical)',1,
     'Tactical command vehicle; 2-4 workstations; radios; basic display',
     '2-4 workstations, radios, basic display, SUV/van'),

    # ── LAW ENFORCEMENT ───────────────────────────────────────────────────────
    ('7-508-1001','Law Enforcement Patrol','Type I','Law Enforcement','Law Enforcement',
     'Law Enforcement Patrol – Type I (Marked Vehicle)',2,
     'Marked patrol vehicle; 2 officers; full law enforcement authority; mobile data terminal',
     '2 officers, marked vehicle, MDT, full LE authority'),
    ('7-508-1002','Law Enforcement Patrol','Type II','Law Enforcement','Law Enforcement',
     'Law Enforcement Patrol – Type II (Single Officer)',1,
     'Marked patrol; 1 officer; full LE authority',
     '1 officer, marked vehicle, full LE authority'),
    ('7-508-1010','Law Enforcement Tactical Team','Type I','Law Enforcement','Law Enforcement',
     'Law Enforcement Tactical Team – Type I (SWAT/SRT)',10,
     'Full tactical team; SWAT/SRT; hostage rescue; high-risk warrant; armored vehicle',
     '10+ personnel, SWAT/SRT, armored vehicle, specialty weapons'),
    ('7-508-1011','Law Enforcement Tactical Team','Type II','Law Enforcement','Law Enforcement',
     'Law Enforcement Tactical Team – Type II (Entry Team)',6,
     'Entry team capability; high-risk warrant; less-lethal; ballistic protection',
     '6 personnel, entry capability, less-lethal, ballistic gear'),
    ('7-508-1020','Motorcycle Unit','Type I','Law Enforcement','Law Enforcement',
     'Motorcycle Unit – Type I (Escort/Traffic)',1,
     'Police motorcycle; traffic control; escort operations; public address',
     '1 officer, police motorcycle, traffic control'),
    ('7-508-1030','Mounted Unit','Type I','Law Enforcement','Law Enforcement',
     'Mounted (Horse) Patrol Unit',1,
     'Mounted police officer; crowd control; terrain; 1 officer + 1 horse',
     '1 officer + horse, crowd control, terrain access'),

    # ── TRANSPORTATION ────────────────────────────────────────────────────────
    ('5-508-2001','Bus','Type I','Transportation','Mass Care Services',
     'Bus – Type I (Over-the-Road Coach)',1,
     'Over-the-road coach; 50+ passenger; ADA accessible; luggage storage',
     '50+ passengers, ADA lift, luggage, 500+ mile range'),
    ('5-508-2002','Bus','Type II','Transportation','Mass Care Services',
     'Bus – Type II (Transit/City Bus)',1,
     'Transit bus; 40 passenger standard; ADA accessible; urban',
     '40 passengers, ADA, urban operations'),
    ('5-508-2003','Bus','Type III','Transportation','Mass Care Services',
     'Bus – Type III (School Bus)',1,
     'School bus; 48-72 passenger; standard school operations',
     '48-72 passengers, standard school bus'),
    ('5-508-2010','Ambulance Bus','Type I','Transportation','Emergency Medical Services',
     'Ambulance Bus – Type I',5,
     'Mass casualty transport; 10+ litter patients or 40 ambulatory; medical staff',
     '5 medical personnel, 10+ litter or 40 ambulatory patients'),
    ('5-508-2011','Ambulance Bus','Type II','Transportation','Emergency Medical Services',
     'Ambulance Bus – Type II',3,
     'MCI transport; 6-10 litter patients or 24 ambulatory',
     '3 medical personnel, 6-10 litter or 24 ambulatory'),

    # ── UTILITIES / POWER ─────────────────────────────────────────────────────
    ('5-508-3001','Fuel Tender','Type I','Logistics','Public Works and Engineering',
     'Fuel Tender – Type I (Large)',1,
     'Large fuel tender; 5000+ gal capacity; pump; aviation/diesel/gas',
     '5000+ gal, multi-fuel capable, pump, DEF capable'),
    ('5-508-3002','Fuel Tender','Type II','Logistics','Public Works and Engineering',
     'Fuel Tender – Type II (Medium)',1,
     'Medium fuel tender; 2000-5000 gal; pump; diesel/gas',
     '2000-5000 gal, pump, diesel/gas'),
    ('5-508-3003','Fuel Tender','Type III','Logistics','Public Works and Engineering',
     'Fuel Tender – Type III (Small)',1,
     'Small fuel tender; 500-2000 gal; diesel/gas',
     '500-2000 gal, pump, diesel or gas'),

    # ── UAS / UNMANNED ────────────────────────────────────────────────────────
    ('8-508-2001','UAS Team','Type I','UAS','Search and Rescue',
     'Unmanned Aircraft System (UAS) Team – Type I',2,
     'Large UAS; thermal and optical; >45 min endurance; Part 107 certified crew; night capable',
     '2 crew (pilot + observer), large UAS, thermal, 45+ min, night ops'),
    ('8-508-2002','UAS Team','Type II','UAS','Search and Rescue',
     'Unmanned Aircraft System (UAS) Team – Type II',1,
     'Medium UAS; optical payload; 30 min endurance; Part 107 certified pilot',
     '1-2 crew, medium UAS, optical, 30 min endurance'),
    ('8-508-2003','UAS Team','Type III','UAS','Search and Rescue',
     'Unmanned Aircraft System (UAS) Team – Type III',1,
     'Small/consumer UAS; optical; <30 min; basic Part 107; daylight only',
     '1 pilot, small/consumer UAS, daylight only, optical'),
]

if __name__ == '__main__':
    print(f"Total resource types defined: {len(NIMS_RESOURCE_TYPES)}")
    cats = {}
    for r in NIMS_RESOURCE_TYPES:
        cats[r[3]] = cats.get(r[3],0)+1
    for cat,cnt in sorted(cats.items()):
        print(f"  {cat}: {cnt}")
